/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Aamir
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTB = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        btitleTF = new javax.swing.JTextField();
        bauthorTF = new javax.swing.JTextField();
        bpublisherTF = new javax.swing.JTextField();
        bpriceTF = new javax.swing.JTextField();
        bidTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        baddTF = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        bsearchBT = new javax.swing.JButton();
        bremoveBT = new javax.swing.JButton();
        bupdateBT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ssearchTF = new javax.swing.JTextField();
        sseachBT = new javax.swing.JButton();
        sremoveBT = new javax.swing.JButton();
        supdateBT = new javax.swing.JButton();
        snameTF = new javax.swing.JTextField();
        srollnoTF = new javax.swing.JTextField();
        sdeptTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        saddBT = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        inameTF = new javax.swing.JTextField();
        ititleTF = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        discardBT = new javax.swing.JButton();
        saveBT = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dBox = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        closeBT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Script MT Bold", 0, 10)); // NOI18N
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Book.books=Book.readList();
        String[][] cont=readlist();
        DefaultTableModel tm =new javax.swing.table.DefaultTableModel(cont,  new String [] {
            "Book ID", "Title", "Author", "Publisher", "Price"
        });
        booksTB.setModel(tm );
        jScrollPane1.setViewportView(booksTB);

        jTabbedPane1.addTab("Books Table", jScrollPane1);

        Student.stds=Student.readList();
        String[][] scont=sreadlist();
        DefaultTableModel tm1 =new javax.swing.table.DefaultTableModel(scont,  new String [] {
            "Student Name", "Roll Number", "Department"
        });
        jTable1.setModel(tm1);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Student Table", jPanel11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Title");

        jLabel2.setText("Author");

        jLabel3.setText("Publisher");

        jLabel4.setText("Price");

        jLabel5.setText("ID");

        baddTF.setText("Add Book");
        baddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddTFActionPerformed(evt);
            }
        });

        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        bsearchBT.setText("Search Book");
        bsearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchBTActionPerformed(evt);
            }
        });

        bremoveBT.setText("Remove Book");
        bremoveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremoveBTActionPerformed(evt);
            }
        });

        bupdateBT.setText("Update Book");
        bupdateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateBTActionPerformed(evt);
            }
        });

        jLabel11.setText("Enter Book title:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btitleTF)
                                            .addComponent(bauthorTF)
                                            .addComponent(bpublisherTF)
                                            .addComponent(bpriceTF)
                                            .addComponent(bidTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(baddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel11)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bremoveBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsearchBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bupdateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(bsearchBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bremoveBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bupdateBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bauthorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpublisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(baddTF)
                .addGap(12, 12, 12))
        );

        jTabbedPane2.addTab("Book", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        sseachBT.setText("Search Student");
        sseachBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sseachBTActionPerformed(evt);
            }
        });

        sremoveBT.setText("Remove Student");
        sremoveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sremoveBTActionPerformed(evt);
            }
        });

        supdateBT.setText("Update");
        supdateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supdateBTActionPerformed(evt);
            }
        });

        jLabel6.setText("Name");

        jLabel7.setText("Roll NO");

        jLabel8.setText("Dept");

        saddBT.setText("Add Student");
        saddBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saddBTActionPerformed(evt);
            }
        });

        jLabel10.setText("Enter Roll Numer:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(snameTF)
                            .addComponent(srollnoTF)
                            .addComponent(sdeptTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ssearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supdateBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sremoveBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sseachBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saddBT)
                .addGap(82, 82, 82))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addComponent(ssearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sseachBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sremoveBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supdateBT)
                .addGap(70, 70, 70)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srollnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdeptTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(saddBT)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Student", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        inameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inameTFActionPerformed(evt);
            }
        });

        jButton11.setText("Issue Book");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel12.setText("Enter Roll Number");

        jLabel13.setText("Enter Book Title");

        jButton1.setText("View Issued");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ititleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(93, 93, 93))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ititleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
        );

        jTabbedPane2.addTab("Issue", jPanel9);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        discardBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        discardBT.setText("Discard Changes");
        discardBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardBTActionPerformed(evt);
            }
        });

        saveBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBT.setText("Save Changes");
        saveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discardBT)
                .addGap(27, 27, 27)
                .addComponent(saveBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discardBT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        dBox.setEditable(false);
        dBox.setColumns(20);
        dBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        dBox.setRows(5);
        jScrollPane2.setViewportView(dBox);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 0, 102));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel6MouseMoved(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        closeBT.setBackground(new java.awt.Color(102, 0, 102));
        closeBT.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        closeBT.setText("X");
        closeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Aamir's Library Management System");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBT))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeBT, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel14.setText("Notification Area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void closeBTActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.dispose();
        // TODO add your handling code here:
    }                                       

    private void saveBTActionPerformed(java.awt.event.ActionEvent evt) {                                       
 // Object[][] acont=new Object[booksTB.getRowCount()][5];
Book.books.clear();
Student.stds.clear();
/*  for(int i=1;i<booksTB.getRowCount();i++){
      Book b=new Book();
b.setID((String) booksTB.getValueAt(i,1));
b.setTitle((String)  booksTB.getValueAt(i,2));
b.setAuthor((String) booksTB.getValueAt(i,3));
b.setPublisher((String) booksTB.getValueAt(i,4));
b.setPrice(Integer.parseInt((String) booksTB.getValueAt(i,5)));
  Book.books.add(b);}*/

//  Book.saveList();
{BufferedWriter bw=null;
		FileWriter fw=null;
		try {
			File file=new File(Book.FILENAME);
                        if(file.exists()) {
			    file.createNewFile();
			}
			fw=new FileWriter(file.getAbsoluteFile(),false);
			bw=new BufferedWriter(fw);
                        for(int i=0;i<booksTB.getRowCount();i++) {
			bw.write(booksTB.getValueAt(i,0)+",");
			bw.write(booksTB.getValueAt(i,1)+",");
			bw.write(booksTB.getValueAt(i,2)+",");
			bw.write(booksTB.getValueAt(i,3)+",");
			bw.write(booksTB.getValueAt(i,4)+"");
			bw.newLine();
			}bw.close();
			}
			catch(IOException e) {
				e.printStackTrace();
			}/*
			finally {
				try {
					if(bw!= null)
						bw.close();
					if(fw!= null)
						fw.close();
				}
				catch(IOException e) {
					e.printStackTrace();
				}
			}  */
}
// TODO add your handling code here:
                BufferedWriter bw=null;
		FileWriter fw=null;
		try {
			File file=new File(Student.sFILENAME);
			if(file.exists()) {
			file.createNewFile();
			}
			fw=new FileWriter(file.getAbsoluteFile(),false);
			bw=new BufferedWriter(fw);
			for(int i=0;i<jTable1.getRowCount();i++) {
			bw.write(jTable1.getValueAt(i,0)+",");
			bw.write(jTable1.getValueAt(i,1)+",");
			bw.write(jTable1.getValueAt(i,2)+"");
			bw.newLine();
			}
			bw.close();
			}
			catch(IOException e) {
				e.printStackTrace();
			}/*
			finally {
				try {
					if(bw!= null)
						bw.close();
					if(fw!= null)
						fw.close();
				}
				catch(IOException e) {
					e.printStackTrace();
				}
			}*/
    }                                      
public String atitle;
public void bt(){
    String[][] cont=new String[Book.books.size()][5];
for(int i=0;i<Book.books.size();i++){
cont[i][0]=Book.books.get(i).getID();
cont[i][1]=Book.books.get(i).getTitle();
cont[i][2]=Book.books.get(i).getAuthor();
cont[i][3]=Book.books.get(i).getPublisher();
String temp=(Book.books.get(i).getPrice()+"");
cont[i][4]=(temp);}
booksTB.setModel(new javax.swing.table.DefaultTableModel(
    cont,
    new String [] {
        "Book ID", "Title", "Author", "Publisher", "Price"
    }
));

}
    private void discardBTActionPerformed(java.awt.event.ActionEvent evt) {                                          
this.dispose();
        // TODO add your handling code here:
    }                                         

    private void formMousePressed(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
    }                                 
int posX=0,posY=0;
    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {                                     
      posX=evt.getX();
posY=evt.getY();// TODO add your handling code here:
    }                                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        for(int i=0;i<Student.stds.size();i++) {
            for(int j=0;j<Student.stds.get(i).booksissued.size();j++) {
                if(Student.stds.get(i).booksissued.get(j)!=null)
                dBox.setText(Student.stds.get(i).getName()+"---HAS---"+Student.stds.get(i).booksissued.get(j));
            }
        }// TODO add your handling code here:
    }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String iname,ibook;
        iname=inameTF.getText();
        ibook=ititleTF.getText();
        int i=searchST(iname);
        int j=searchBK(ibook);
        if(i>=0&&j>=0){
            dBox.setText("Book Issued!"+iname+"----"+ibook);
            Student.stds.get(i).booksissued.add(Book.books.get(j).getTitle());
        }else if(i>=0&&j<0)
        dBox.setText("Book is not found...");
        else if(i<0&&j>=0)
        dBox.setText("Student is not found...");
        else
        dBox.setText("Book and Student both are invalid!");
        // TODO add your handling code here:
    }                                         

    private void inameTFActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void saddBTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Student b=new Student();
        b.setName(snameTF.getText());
        b.setRollno(srollnoTF.getText());
        b.setDeptt(sdeptTF.getText());

        Student.stds.add(b);
        supdateTB();
        // TODO add your handling code here:
    }                                      

    private void supdateBTActionPerformed(java.awt.event.ActionEvent evt) {                                          
        supdateTB();    // TODO add your handling code here:
    }                                         

    private void sremoveBTActionPerformed(java.awt.event.ActionEvent evt) {                                          
        sseachBTActionPerformed(evt);
        Student.stds.remove(sindex);
        // TODO add your handling code here:
    }                                         

    private void sseachBTActionPerformed(java.awt.event.ActionEvent evt) {                                         
      
        aname=ssearchTF.getText();
        int i=searchST(aname);
    }                                        

    private void bupdateBTActionPerformed(java.awt.event.ActionEvent evt) {                                          
        updateTB();        // TODO add your handling code here:
    }                                         

    private void bremoveBTActionPerformed(java.awt.event.ActionEvent evt) {                                          
        atitle=searchTF.getText();
        int index=-1;
        for(int i=0;i<Book.books.size();i++){
            if(atitle.equalsIgnoreCase(Book.books.get(i).getTitle()))
            index=i;
        }
        if(index>=0){
            dBox.setBackground(Color.GREEN);
            dBox.setText("Book Found!\n"+Book.books.get(index).getTitle()+"-----"+Book.books.get(index).getID());
            booksTB.changeSelection(index, 1, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
            Book.books.remove(index);
            updateTB();
        }else{
            dBox.setBackground(Color.RED);
            dBox.setText("Book not found Found!");
        }        // TODO add your handling code here:
    }                                         

    private void bsearchBTActionPerformed(java.awt.event.ActionEvent evt) {                                          
        atitle=searchTF.getText();
        int i=searchBK(atitle);
        // TODO add your handling code here:
    }                                         

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {                                         

        // TODO add your handling code here:
    }                                        

    private void baddTFActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Book b=new Book();
        b.setTitle(btitleTF.getText());
        b.setAuthor(bauthorTF.getText());
        b.setPublisher(bpublisherTF.getText());
        b.setPrice(Integer.parseInt(bpriceTF.getText()));
        b.setID("ULB0"+(Book.books.size()+1));
        Book.books.add(b);
        updateTB();
        // TODO add your handling code here:
    }                                      

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {                                     
setLocation(evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);        
// TODO add your handling code here:
    }                                    

    private void jPanel6MouseMoved(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
    }                                  
String aname;
int sindex;public String[][] readlist(){
    String[][] cont=new String[Book.books.size()][5];
for(int i=0;i<Book.books.size();i++){
cont[i][0]=Book.books.get(i).getID();
cont[i][1]=Book.books.get(i).getTitle();
cont[i][2]=Book.books.get(i).getAuthor();
cont[i][3]=Book.books.get(i).getPublisher();
String temp=(Book.books.get(i).getPrice()+"");
cont[i][4]=(temp);}
return cont;
}
public void updateTB(){
    String[][] cont=readlist();
DefaultTableModel tm =new javax.swing.table.DefaultTableModel(cont,  new String [] {
        "Book ID", "Title", "Author", "Publisher", "Price"
    });
booksTB.setModel(tm );

}
public String[][] sreadlist(){
    
    String[][] scont=new String[Student.stds.size()][3];
for(int i=0;i<Student.stds.size();i++){
scont[i][0]=Student.stds.get(i).getName();
scont[i][1]=Student.stds.get(i).getRollno();
scont[i][2]=Student.stds.get(i).getDeptt();}
return scont;
}
public void supdateTB(){

    String[][] scont=sreadlist();
DefaultTableModel tm =new javax.swing.table.DefaultTableModel(scont,  new String [] {
        "Student Name", "Roll Number", "Department"
    });
jTable1.setModel(tm );    
}
public int searchST(String aname){
     int index=-1;
for(int i=0;i<Student.stds.size();i++){
if(aname.equalsIgnoreCase(Student.stds.get(i).getRollno()))
        index=i;
        }
if(index>=0){
    dBox.setBackground(Color.GREEN);
dBox.setText("Student Found!\n"+Student.stds.get(index).getName()+"-----"+Student.stds.get(index).getDeptt());
jTable1.changeSelection(index, 1, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
sindex=index;
}else{
    dBox.setBackground(Color.RED);
    dBox.setText("Student not found Found!");
}return index;
// TODO add your handling code here:
}
public int searchBK(String atitle){
            int index=-1;
for(int i=0;i<Book.books.size();i++){
if(atitle.equalsIgnoreCase(Book.books.get(i).getTitle()))
        index=i;
        }
if(index>=0){
    dBox.setBackground(Color.GREEN);
dBox.setText("Book Found!\n"+Book.books.get(index).getTitle()+"-----"+Book.books.get(index).getID());
booksTB.changeSelection(index, 1, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
}else{
    dBox.setBackground(Color.RED);
    dBox.setText("Book not found Found!");
} return index;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
               
       // Student.readList();
       // Book.readList();
        
        NewJFrame jf=new NewJFrame();       
       jf.setVisible(true);}
            
        });
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton baddTF;
    private javax.swing.JTextField bauthorTF;
    private javax.swing.JTextField bidTF;
    private javax.swing.JTable booksTB;
    private javax.swing.JTextField bpriceTF;
    private javax.swing.JTextField bpublisherTF;
    private javax.swing.JButton bremoveBT;
    private javax.swing.JButton bsearchBT;
    private javax.swing.JTextField btitleTF;
    private javax.swing.JButton bupdateBT;
    private javax.swing.JButton closeBT;
    private javax.swing.JTextArea dBox;
    private javax.swing.JButton discardBT;
    private javax.swing.JTextField inameTF;
    private javax.swing.JTextField ititleTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saddBT;
    private javax.swing.JButton saveBT;
    private javax.swing.JTextField sdeptTF;
    private javax.swing.JTextField searchTF;
    private javax.swing.JTextField snameTF;
    private javax.swing.JButton sremoveBT;
    private javax.swing.JTextField srollnoTF;
    private javax.swing.JButton sseachBT;
    private javax.swing.JTextField ssearchTF;
    private javax.swing.JButton supdateBT;
    // End of variables declaration                   
}
